import { PortInfo } from '../core/types';

export const demoPortData: PortInfo[] = [
  {
    port: 22,
    protocol: 'tcp',
    state: 'LISTEN',
    localAddress: '0.0.0.0:22',
    remoteAddress: null,
    pid: 1234,
    process: 'sshd',
    user: 'root',
    source: 'netstat',
  },
  {
    port: 80,
    protocol: 'tcp',
    state: 'LISTEN',
    localAddress: '0.0.0.0:80',
    remoteAddress: null,
    pid: 2345,
    process: 'nginx',
    user: 'www-data',
    source: 'netstat',
  },
  {
    port: 443,
    protocol: 'tcp',
    state: 'LISTEN',
    localAddress: '0.0.0.0:443',
    remoteAddress: null,
    pid: 2345,
    process: 'nginx',
    user: 'www-data',
    source: 'netstat',
  },
  {
    port: 3000,
    protocol: 'tcp',
    state: 'LISTEN',
    localAddress: '127.0.0.1:3000',
    remoteAddress: null,
    pid: 3456,
    process: 'node',
    user: 'developer',
    source: 'netstat',
  },
  {
    port: 5432,
    protocol: 'tcp',
    state: 'LISTEN',
    localAddress: '127.0.0.1:5432',
    remoteAddress: null,
    pid: 4567,
    process: 'postgres',
    user: 'postgres',
    source: 'netstat',
  },
  {
    port: 6379,
    protocol: 'tcp',
    state: 'LISTEN',
    localAddress: '127.0.0.1:6379',
    remoteAddress: null,
    pid: 5678,
    process: 'redis-server',
    user: 'redis',
    source: 'netstat',
  },
  {
    port: 8080,
    protocol: 'tcp',
    state: 'LISTEN',
    localAddress: '0.0.0.0:8080',
    remoteAddress: null,
    pid: 6789,
    process: 'java',
    user: 'tomcat',
    source: 'netstat',
  },
  {
    port: 27017,
    protocol: 'tcp',
    state: 'LISTEN',
    localAddress: '127.0.0.1:27017',
    remoteAddress: null,
    pid: 7890,
    process: 'mongod',
    user: 'mongodb',
    source: 'netstat',
  },
  {
    port: 443,
    protocol: 'tcp',
    state: 'ESTABLISHED',
    localAddress: '192.168.1.100:52341',
    remoteAddress: '142.250.185.46:443',
    pid: 8901,
    process: 'chrome',
    user: 'developer',
    source: 'netstat',
  },
  {
    port: 443,
    protocol: 'tcp',
    state: 'ESTABLISHED',
    localAddress: '192.168.1.100:52342',
    remoteAddress: '151.101.1.140:443',
    pid: 8901,
    process: 'chrome',
    user: 'developer',
    source: 'netstat',
  },
  {
    port: 22,
    protocol: 'tcp',
    state: 'ESTABLISHED',
    localAddress: '192.168.1.100:22',
    remoteAddress: '192.168.1.50:58432',
    pid: 1234,
    process: 'sshd',
    user: 'root',
    source: 'netstat',
  },
  {
    port: 53,
    protocol: 'udp',
    state: 'LISTEN',
    localAddress: '127.0.0.53:53',
    remoteAddress: null,
    pid: 9012,
    process: 'systemd-resolved',
    user: 'systemd-resolve',
    source: 'netstat',
  },
  {
    port: 68,
    protocol: 'udp',
    state: 'LISTEN',
    localAddress: '0.0.0.0:68',
    remoteAddress: null,
    pid: null,
    process: null,
    user: null,
    source: 'netstat',
  },
  {
    port: 5353,
    protocol: 'udp',
    state: 'LISTEN',
    localAddress: '0.0.0.0:5353',
    remoteAddress: null,
    pid: 1123,
    process: 'avahi-daemon',
    user: 'avahi',
    source: 'netstat',
  },
];

export function getDemoData() {
  return {
    ports: demoPortData,
    timestamp: new Date().toISOString(),
    platform: 'linux (demo)',
  };
}
